### ISSUE TITLE
本地图片上传调用该模型报错T：TypeError: Invalid URL

### ISSUE THREAD

**Issue by ruthy-wei** [LLM-Red-Team/kimi-free-api#146]
报错信息如下：
服务器端：
[2024-11-12 18:07:28.382][info][index<971,30>] <- POST /v1/chat/completions 10091ms
[2024-11-13 10:00:02.207][info][index<1001,26>] -> POST /v1/chat/completions
[2024-11-13 10:00:02.207][info][index<1254,20>] [ { role: 'user', content: [ [Object], [Object] ] } ]
[2024-11-13 10:00:02.207][info][index<1396,18>] 本次请求上传：1个文件
[2024-11-13 10:00:02.208][error][index<1292,22>] Stream response error: Invalid URL
[2024-11-13 10:00:02.208][warning][index<1293,22>] Try again after 5s...
[2024-11-13 10:00:07.209][info][index<1254,20>] [ { role: 'user', content: [ [Object], [Object] ] } ]
[2024-11-13 10:00:07.209][info][index<1396,18>] 本次请求上传：1个文件
[2024-11-13 10:00:07.212][error][index<1292,22>] Stream response error: Invalid URL
[2024-11-13 10:00:07.212][warning][index<1293,22>] Try again after 5s...
[2024-11-13 10:00:12.213][info][index<1254,20>] [ { role: 'user', content: [ [Object], [Object] ] } ]
[2024-11-13 10:00:12.214][info][index<1396,18>] 本次请求上传：1个文件
[2024-11-13 10:00:12.217][error][index<1292,22>] Stream response error: Invalid URL
[2024-11-13 10:00:12.217][warning][index<1293,22>] Try again after 5s...
[2024-11-13 10:00:17.217][info][index<1254,20>] [ { role: 'user', content: [ [Object], [Object] ] } ]
[2024-11-13 10:00:17.218][info][index<1396,18>] 本次请求上传：1个文件
[2024-11-13 10:00:17.220][error][index<1020,28>] TypeError: Invalid URL
    at new URL (node:internal/url:806:29)
    at dispatchHttpRequest (file:///app/node_modules/axios/lib/adapters/http.js:232:20)
    at file:///app/node_modules/axios/lib/adapters/http.js:152:5
    at new Promise (<anonymous>)
    at wrapAsync (file:///app/node_modules/axios/lib/adapters/http.js:132:10)
    at http (file:///app/node_modules/axios/lib/adapters/http.js:170:10)
    at Axios.dispatchRequest (file:///app/node_modules/axios/lib/core/dispatchRequest.js:51:10)
    at Axios._request (file:///app/node_modules/axios/lib/core/Axios.js:173:33)
    at Axios.request (file:///app/node_modules/axios/lib/core/Axios.js:40:25)
    at Axios.<computed> [as head] (file:///app/node_modules/axios/lib/core/Axios.js:199:17)
    at Axios.request (file:///app/node_modules/axios/lib/core/Axios.js:45:41)
    at async checkFileUrl (file:///app/dist/index.js:1476:18)
    at async uploadFile (file:///app/dist/index.js:1489:3)
    at async Promise.all (index 0)
    at async file:///app/dist/index.js:1256:39
    at async /completions (file:///app/dist/index.js:1781:16) {
  code: 'ERR_INVALID_URL',
客户端调用代码kimi_free_test.py：
def get_kimi_free_image(token):
    client = OpenAI(
        api_key=token,
        base_url="http://10.88.7.42:8000/v1",
    )
    response = client.chat.completions.create(
        model="kimi",  # Fill in the model name to be called
        messages=[
            {
                "role": "user",
                "content": [
                {
                    "type": "image_url",
                    "image_url": {
                        "url": image_base64
                    }
                },
                {
                    "type": "text",
                    "text": "描述这张图片"
                }
                ]
            },
       ]
    )
    return response.choices[0].message.content
def encode_image(image_path):
        #对图像进行编码
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

image_path = "./Upload_file/review_sheet/1.审查申报表/page_0.png"
base64_image = encode_image(image_path)
result= get_kimi_free_image(token,base64_image)
print(result)

返回结果为：
Traceback (most recent call last):
  File "/home/ecadi/whh/OutGaugeRecognition/kimi_free_test.py", line 109, in <module>
    result= get_kimi_free_image(token,base64_image)
  File "/home/ecadi/whh/OutGaugeRecognition/kimi_free_test.py", line 89, in get_kimi_free_image
    return response.choices[0].message.content
TypeError: 'NoneType' object is not subscriptable
如果把上述代码的 image_base64换成一个URL路径就可以正常访问，是不支持本地图片上传嘛？

**Comment by Vinlic** [comment]
base64需要增加data头，比如data:image/jpeg;base64,....
