### ISSUE TITLE
服务请求失败

### ISSUE THREAD

**Issue by x20000826** [LLM-Red-Team/kimi-free-api#68]
[2024-04-19 14:57:48.477][error][index<1212,61>] APIException [Error]: [请求kimi失败]: 服务内部错误
    at checkResult (file:///app/dist/index.js:1482:9)
    at file:///app/dist/index.js:1139:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestToken (file:///app/dist/index.js:1126:18)
    at async acquireToken (file:///app/dist/index.js:1166:14)
    at async fakeRequest (file:///app/dist/index.js:1288:17) {
  errcode: -2001,
  errmsg: '[请求kimi失败]: 服务内部错误',
  data: undefined,
  httpStatusCode: undefined
不知道是什么原因，是我的token输入错了吗？我核对了好几遍

**Comment by Vinlic** [comment]
@chunzha1 目前不可

**Comment by chunzha1** [comment]
> @chunzha1 目前不可

好吧，感谢

**Comment by x20000826** [comment]
> 一轮

好难受哈哈哈，我今天下午才注册的号

**Comment by waqian** [comment]
应该是封号了，大家都一样的。

**Comment by figo2025** [comment]
我在一次请求中，报了错但又返回了正确结果，日志如下
`kimi-free-api  |   errcode: -2001,
0|kimi-free-api  |   errmsg: '[请求kimi失败]: 服务内部错误',
0|kimi-free-api  |   data: undefined,
0|kimi-free-api  |   httpStatusCode: undefined
0|kimi-free-api  | }
0|kimi-free-api  | [2025-02-19 17:15:25.855][success][chat.ts<379,12>] Stream has completed transfer 16938ms
0|kimi-free-api  | [2025-02-19 17:15:25.857][info][chat.ts<153,10>] url: /api/chat/cuqq24s432e4r2m3gbkg
0|kimi-free-api  | [2025-02-19 17:15:25.864][info][server.ts<66,36>] <- POST /v1/chat/completions 17152ms`

**Comment by figo2025** [comment]
补充下日志

0|kimi-free-api  | [2025-02-19 17:15:08.796][info][chat.ts<326,12>] 使用模型: k1，是否联网检索: false，是否探索版: false，是否K1模型: true，是否数学模型: false
0|kimi-free-api  | [2025-02-19 17:15:08.796][info][chat.ts<153,10>] url: /api/user/usage
0|kimi-free-api  | [2025-02-19 17:15:08.798][info][chat.ts<153,10>] url: /api/chat/cuqq24s432e4r2m3gbkg/pre-n2s
0|kimi-free-api  | [2025-02-19 17:15:08.799][info][chat.ts<153,10>] url: /api/suggestion
0|kimi-free-api  | [2025-02-19 17:15:08.801][info][chat.ts<153,10>] url: /api/chat/cuqq24s432e4r2m3gbkg/token_size
0|kimi-free-api  | [2025-02-19 17:15:08.802][info][chat.ts<153,10>] url: /api/chat/cuqq24s432e4r2m3gbkg/completion/stream
0|kimi-free-api  | [2025-02-19 17:15:08.880][error][chat.ts<315,28>] APIException [Error]: [请求kimi失败]: 服务内部错误
